### ISSUE TITLE
[Event Tracking] Add mixpanel event tracking

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#371]
https://app.gitbook.com/o/btnrCjBfFA1CijnAHf9d/s/uD5IIQEzBNOcwceEz9qr/

**Comment by Peppermint1020** [comment]
- [x] Super event
- [x] Identify User
After switch profile, distinct id changed.
![Image](https://github.com/user-attachments/assets/97ce93fe-8792-4108-ab55-f01b769670e3)

- [ ] Script Error
never trigger this issue
- [x] Delegation Created
![Image](https://github.com/user-attachments/assets/761b5e52-7d73-4436-9c17-8bce64b3e79b)

- [x] On Ramp Clicked
![Image](https://github.com/user-attachments/assets/9b22fd0d-186a-4e95-8554-e84cafca7e7c)

- [x] COA Creation
![Image](https://github.com/user-attachments/assets/8ca7b17c-efdd-4474-9447-a69e09f52367)

- [x] Security Tool
![Image](https://github.com/user-attachments/assets/42ff5412-3248-4a15-b649-703abb1324b3)

- [x] Multi-Backup Created
![Image](https://github.com/user-attachments/assets/54b577f3-af55-49ed-b8fb-97ed4089d0c7)

- [x] Multi-Backup Creation Failed
![Image](https://github.com/user-attachments/assets/34a65148-bfac-4f51-8534-c0a4c5767833)

- [ ] Cadence Transaction Signed
- [x] EVM Transaction Signed
![Image](https://github.com/user-attachments/assets/fb9fdd6e-3c16-44fb-acb9-b360415aebbb)

- [x] FT Transfer
![Image](https://github.com/user-attachments/assets/e11a7758-0cf6-42b7-83e4-2e7eb9095b0f)

- [x] NFT Transfer
![Image](https://github.com/user-attachments/assets/60e15323-36bb-4e36-b5de-582a4f7facc8)

- [x] Transaction Result
![Image](https://github.com/user-attachments/assets/7f37b589-b118-4abe-87e1-34d7433a9b5d)

- [x] Account Created
![Image](https://github.com/user-attachments/assets/be450e1d-4928-46c2-8514-f0b288ff9657)
- [x] Account Recovered
![Image](https://github.com/user-attachments/assets/1b074d08-27f4-4002-b308-9ab8a1ebc2ce)

- [x] Account Creation Time  
![Image](https://github.com/user-attachments/assets/c02838a8-ef4d-4395-9ab6-9221ad4a4530)
When switch account or recovery account, account create time triggered incorrectly.


Question for this feature:
(1) Cadence transaction is not triggered when use flow port transfer token

**Comment by Peppermint1020** [comment]
Tested on iOS prod version 2.2.12(4).
Pass all tests
